import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AOSProvider } from "@/components/ui/aos-provider";
import Footer from "@/components/ui/footer";
import Header from "@/components/ui/header";
import { RegionHeader } from "@/components/ui/region-header";
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-white">
      {/* <Header1 /> */}
      {/* <Header /> */}
      <RegionHeader />
      {children}
      <Footer />
    </div>
  );
}
